### ISSUE TITLE
S'y rendre : image de fond à revoir

### ISSUE THREAD

**Issue by nicolasmingo** [agilepaysbasque/site-web#17]

**Comment by aliceb64** [comment]
ATTENTION : il y a 2 lieux:
- Vendredi : ESTIA/Bidart
- Samedi : ATLANTHAL/Anglet

**Comment by nicolasmingo** [comment]
> ATTENTION : il y a 2 lieux:
> Vendredi : ESTIA/Bidart
> Samedi : ATLANTHAL/Anglet

J'ai ouvert une autre issue
