### ISSUE TITLE
Accueil > Dernières news

### ISSUE THREAD

**Issue by nicolasmingo** [agilepaysbasque/site-web#2]
Montrer les twits du flux d'agile pays basque

**Comment by Squallygator** [comment]
**Intégration via Widget sur Twitter :**
CF [https://support.twitter.com/articles/20171531](https://support.twitter.com/articles/20171531)
`    <a class="twitter-timeline" data-lang="fr" data-height="500" data-theme="dark" href="https://twitter.com/agilepb">Tweets by agilepb</a>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
`

**Comment by nicolasmingo** [comment]
ça a l'air de fonctionner

**Comment by Squallygator** [comment]
ça s'affiche pas comme il faudrait, il faut trouver une parade CSS je pense ou changer la structure
