### ISSUE TITLE
Accueil > C'est quoi

### ISSUE THREAD

**Issue by nicolasmingo** [agilepaysbasque/site-web#4]

**Comment by Squallygator** [comment]
**Ecrire le contenu "C'est quoi - Ateliers" et l'implémenter**

_Remplacer le contenu par défaut par:_ 
> 5 ateliers permettant de découvrir ou d'approfondir des pratiques agiles en lien avec les thématiques des conférences

_Remplacer_  
> Cest quoi
_par_
> Pourquoi venir à Agile Pays Basque?

CF [TRELLO](https://trello.com/c/B67Wh5Vc)

**Comment by Squallygator** [comment]
**Ecrire le contenu "C'est quoi - Conférences" et l'implémenter**

_Remplacer le titre par défaut par_
>Conférences

_Remplacer le texte par défaut par: _

> 19 conférences réparties sur 3 thématiques "Culture Agile et Management", "Découverte et Conception de Produits" et "Développement Logiciel et Tests". Débutants bienvenus!

**Comment by Squallygator** [comment]
**Ecrire le contenu "C'est quoi - Forum Ouvert" et et l'implémenter**

_Remplacer le titre par défaut par_
> Forum Ouvert

_Remplacer le contenu par défaut par: _

> 1 journée avec un programme co-construit le jour même entre les speakers et les participants, pour augmenter la variété des thématiques ou les approfondir
CF [Trello](https://trello.com/c/RiQBlsS3)
