### ISSUE TITLE
Lieu

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#44]
ES*** est trop gros. On dirait que c'est l'ES*** qui organise Agile PB. Pour éviter la confusion, serait-il possible d'avoir Association Agile Pays Basque en très gros et dessous ES*** au même niveau que l'adresse ?

**Comment by nicolasmingo** [comment]
On doit ajouter athlantal et les 2 lieux seront au même niveau

**Comment by nicolasmingo** [comment]
On a déjà une issue sur ça : #43

**Comment by nicolasmingo** [comment]
PR #49
