### ISSUE TITLE
Accueil > Lieu

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#45]
Cette section me dérange car on a vraiment le sentiment que c'est l'ES*** qui organise la conf. Il y a déjà des mélanges des genres et il faut vraiment axer la com sur notre indépendance à l'égard de l'ES*** ou autre. Faut-il remplacer cette section par des photos d'Agile PB 2016 et la renommer "Souvenirs" ?

**Comment by Squallygator** [comment]
C'est pas plutôt qu'on mets pas assez les activités de l'asso en avant

**Comment by aliceb64** [comment]
oui il faut axer sur nous. D'ailleurs à ce sujet, si on renomme cette section en "Souvenir" ou autre titre mieux formulé, on peut faire un lien avec AgilePB 2016

**Comment by nicolasmingo** [comment]
les photos sont à redimmensionner de toute façon, car on doit ajouter athlantal et les 2 lieux doivent être au même niveau.

**Comment by nicolasmingo** [comment]
AgilePB 2016 est un autre besoin -> issue à part
