### ISSUE TITLE
Accueil > Billetterie, faire correspondre le style au reste de la page (fonts, couleurs)

### ISSUE THREAD

**Issue by loustau** [agilepaysbasque/site-web#50]

**Comment by Squallygator** [comment]
La billetterie est integré en iframe.
Le style est géré par HelloAsso dans le backend.
Après avoir tester le rendu du tarif dans le template initiale, jugeant le rendu pas terrible, j'ai opté pour l'iframe.

Du coup 2 choix
- On revient aux tarifs en dur avec redirection vers page HelloAsso
- On garde l'iframe mais on tente quelques changement dans le backend

**Comment by nicolasmingo** [comment]
Attention iframe!!! -> pour relooker le contenu d'une iframe -> ....

**Comment by loustau** [comment]
Si on fait "on revient aux tarifs en dur avec redirection vers page HelloAsso » du coup pour les 3 cadres on ferait à gauche le vendredi, au milieu le early bird et à droite le samedi, et tous renvoient vers la même page helloasso. Ca serait pas mal non?

**Comment by nicolasmingo** [comment]
Question posée aux fabricants du widget

**Comment by nicolasmingo** [comment]
On pourrait au pire mettre un fond sombre derrière le widget. (comme le widget twitter)
