### ISSUE TITLE
Acceuil > Twiteer: désactiver le scroll 

### ISSUE THREAD

**Issue by loustau** [agilepaysbasque/site-web#51]
L'usage n'est pas agréable. Quand on scrolle la page si la souris est au milieu, le scroll passe sur twitter et plus sur la page. Il faut déplacer la souris sur un des côtés et recommencer à scroller. Idem sur mobile avec le pouce.

**Comment by Squallygator** [comment]
Je comprends le besoin, mais si on enlève le scoll ça perd de sont intérêt ! (c'est une iframe, gérée par twitter)
Il faudra alors coder un vrai truc pour ne récuperer que les 3 der twitt' par exemple
A creuser

**Comment by loustau** [comment]
Ah oui je vois, mais c’est vraiment hyper pénible… Bon on creusera un peu plus tard

**Comment by loustau** [comment]
L'usage est vraiment problématique. Surtout que ça apparait avant d'être arrivé à la biletterie. Pour moi une solution si on tient absolument à garder le feed twitter c'est de le mettre le plus bas possible dans la page, juste au dessus du footer. Si on y tient vraiment (moi pas spécialement...).

**Comment by nicolasmingo** [comment]
Je sais désactiver tous les events sur le widget, mais pas uniquement le scroll. Ce qui veut dire qu'on ne peut pas cliquer sur les tweets et autres boutons du widget. Je continue à regarder
