### ISSUE TITLE
Orateur > Bouton "Devenir Orateur" à masquer

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#54]

**Comment by aliceb64** [comment]
Ne pointe pas vers le bon CFP
![capture d ecran 2017-06-19 a 22 21 08](https://user-images.githubusercontent.com/6814601/27304207-a5cceeb4-553d-11e7-9c7a-ca26fc2c9266.png)

**Comment by nicolasmingo** [comment]
PR #62
