### ISSUE TITLE
Orateurs > Mettre la trombine des orateurs dans le carré

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#55]

**Comment by nicolasmingo** [comment]
il nous faut toutes les photos. Cf gsheet colonne thumbnailUrl

**Comment by aliceb64** [comment]
https://github.com/agilepaysbasque/site-web/tree/master/img/people
Pascal a sauvegardé la plupart des photos ici. Pour les manquantes, on se créé un avatar "vide".

**Comment by nicolasmingo** [comment]
ok
