### ISSUE TITLE
Accueil > Bouton Acheter un billet à brancher vers la billetterie

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#57]

**Comment by aliceb64** [comment]
Bouton bleu de la barre des menus pointe vers erreur 404
![capture d ecran 2017-06-19 a 22 17 36](https://user-images.githubusercontent.com/6814601/27304072-3422313e-553d-11e7-9b91-1f7599da98fb.png)

**Comment by nicolasmingo** [comment]
PR #64
