### ISSUE TITLE
Accueil > Devenir sponsor à désactiver tant que la rubrique n'est pas finalisée 

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#58]
(ça fait pas partie de la V1 du site)

**Comment by aliceb64** [comment]
![capture d ecran 2017-06-19 a 22 25 30](https://user-images.githubusercontent.com/6814601/27304387-3acc58ec-553e-11e7-8fe1-257e824a28a5.png)

**Comment by nicolasmingo** [comment]
PR #63
