### ISSUE TITLE
Accueil > Programme - renommer agenda

### ISSUE THREAD

**Issue by aliceb64** [agilepaysbasque/site-web#61]
Reprendre l'appellation "Programme" et non pas "Agenda"
Ajouter la mention : Programme provisoire qui peut être soumis à modifications.
![capture d ecran 2017-06-19 a 22 39 37](https://user-images.githubusercontent.com/6814601/27304987-4aa07bf2-5540-11e7-8312-c9af43169bbd.png)

**Comment by nicolasmingo** [comment]
PR #65
