### ISSUE TITLE
Programme > ne correspond pas à celui que nous avons validé ensemble sur slack le 16/6

### ISSUE THREAD

**Issue by loustau** [agilepaysbasque/site-web#75]
https://agile-paysbasque.slack.com/files/vincent/F5U69KC3A/programme_2017_-_20170616_-_propo_finale.xlsx

OK sur le fait que certains ont décliné, par contre il y a des changements de slots que je ne comprends pas (ex. TDD dans la vraie vie est maintenant l'aprèm alors qu'il était le matin).

**Comment by Squallygator** [comment]
Je regarde ce midi pour mettre à jour le planning à trous
